function plotOptimizationInfo(optim, currIter, figId)

[minGlobalQ, indGlob] = min(optim.improvedPop.Quality);
paramSetString = '';
for iParam = 1:optim.problemCfg.nPar
    paramSetString = [paramSetString, '  ' num2str(optim.improvedPop.Population(indGlob, iParam))];
end

figure(figId)
titleCell = {
       '', '', ...
       ['Iteration : ' num2str(currIter.iIter)], ...
        '', ...
       ['Global best quality : ' num2str(minGlobalQ)], ...
       ['Local best quality : ' num2str(min(currIter.quality))], ...
       ['Current population radius : ' num2str(optim.results.clusterRad{currIter.iIter})], ...
       '', ...
       ['Best parameter set : '], ...
       paramSetString, ...
       '', '', '', '', '', '', '', '', ''};
   
title(titleCell);
   
if currIter.iIter == 1
    set(gca,'XColor', 'none','YColor','none')
end

end