%% 4. Plot playback : 

extPlotFun = {@gfx.plotTesfun2DSpacePop, @gfx.plotTesfun2DSpacePopZoom, @gfx.plotQualityContributions, @gfx.plotParamDistribution};

% Run your Optimization code and save the data before running this cell
% here as the second argument put the path of the data to be played back.
% Additionaly the settings as previosly can be set.
optimizer_playback = IGTEOptimizer('PLAYBACK', ... 
                                   'replayDataPath', './Rastrigin_test_function_results/Rastrigin_test_function_run_1_09-Aug-2021_10_50_03.mat', ...
                                   'extPlotFun', extPlotFun, ...
                                   'saveFiguresEveryIter', false, ...
                                   'plotEveryNth', 1);